import Config

# Configure your database
# config :upa_tik_portal, UpaTikPortal.Repo,
#   username: System.get_env("DB_USERNAME", "postgres"),
#   password: System.get_env("DB_PASSWORD", "admin123"),
#   hostname: System.get_env("DB_HOSTNAME", "localhost"),
#   database: System.get_env("DB_DATABASE", "upa_tik_portal_dev"),
#   stacktrace: true,
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :upa_tik_portal, UpaTikPortalWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  url: [host: "localhost", port: 4000],
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "j/c8iJBTcJgSjH+KIsUpGSyqKCCmQPj1nXsSz78KlnMknIDRo86qe4ix1l2zZADh",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:upa_tik_portal, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:upa_tik_portal, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :upa_tik_portal, UpaTikPortalWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/upa_tik_portal_web/router\.ex$",
      ~r"lib/upa_tik_portal_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :upa_tik_portal, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Config MinIO
config :ex_aws,
  access_key_id: System.get_env("MINIO_ACCESS_KEY"),
  secret_access_key: System.get_env("MINIO_SECRET_KEY"),
  region: "us-east-1"

config :ex_aws, :s3,
  scheme: "http://",
  host: System.get_env("MINIO_HOST", "127.0.0.1"),
  port: (System.get_env("MINIO_PORT") || "9000") |> String.to_integer()

# Config Mailer (Gmail SMTP)
# Memuat .env secara manual tanpa library tambahan agar tidak error saat kompilasi
if File.exists?(".env") do
  IO.puts(">>> [System] Memuat konfigurasi dari .env...")

  File.read!(".env")
  |> String.split("\n", trim: true)
  |> Enum.each(fn line ->
    case String.split(line, "=", parts: 2) do
      [key, value] ->
        k = String.trim(key)
        v = String.trim(value)
        System.put_env(k, v)

      _ ->
        :ok
    end
  end)

  IO.puts(">>> [System] .env berhasil dimuat.")
else
  IO.puts(">>> [System] WARNING: File .env tidak ditemukan!")
end

config :upa_tik_portal, UpaTikPortal.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: System.get_env("SMTP_HOST", "smtp.gmail.com"),
  username: System.get_env("SMTP_USER"),
  password: System.get_env("SMTP_PASSWORD"),
  port: String.to_integer(System.get_env("SMTP_PORT", "465")),
  ssl: System.get_env("SMTP_PORT", "465") == "465",
  tls: :if_available,
  auth: :always,
  retries: 2,
  no_mx_lookups: true,
  # PAKSA GLOBAL VERIFY NONE
  tls_options: [verify: :verify_none],
  ssl_options: [verify: :verify_none]
